
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-24T23:02:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7211e63d4c9ccf40d9c3145ed9b71b97c411fcf0",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
