from builtins import str as str2
name: 'str2' = 'std'
version: 'str2' = '0.0.6'
authors: 'str2' = 'Temper Contributors'
description: 'str2' = 'Optional support library provided with Temper'
homepage: 'str2' = 'https://temperlang.dev/'
license: 'str2' = 'Apache-2.0'
repository: 'str2' = 'https://github.com/temperlang/temper'
py_name: 'str2' = 'temper-std'
java_group: 'str2' = 'dev.temperlang'
java_artifact: 'str2' = 'temper-std'
java_package: 'str2' = 'temper.std'
java_dependencies: 'str2' = 'org.junit.jupiter:junit-jupiter:5.9.2'
js_name: 'str2' = '@temperlang/std'
