# coding: utf-8

"""
    Dungeons and Trolls

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dungeons_and_trolls_client.models.dungeonsandtrolls_item_type import DungeonsandtrollsItemType  # noqa: E501

class TestDungeonsandtrollsItemType(unittest.TestCase):
    """DungeonsandtrollsItemType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDungeonsandtrollsItemType(self):
        """Test DungeonsandtrollsItemType"""
        # inst = DungeonsandtrollsItemType()

if __name__ == '__main__':
    unittest.main()
