
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-11T11:46:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5a034974529cbe263fcacfd6e269b6830d3f7e6",
 "version": "0.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
