class Teacher:
    name: str
    def __new__(name:str,sub:str) -> Teacher: ...

    def add_period(period:int,grade:int,section:str) -> None: ...

    def get_sub() -> str: ...



class School:
    ...
    # def teacher_by_subjects(subject:str) -> list: ...