# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_nbdev_broken.ipynb.

# %% auto 0
__all__ = ['super_func']

# %% ../nbs/99_nbdev_broken.ipynb 4
def super_func(
        keyword_or_non_keyword_arg, # this is a keyword or non-keyword arg
        *, 
        keyword_only_arg # this is a keyword only arg 
) -> str: # return string
    "super func"
    ... 


