__title__ = 'xmind2testcase_adaptation'
__description__ = '1、支持xmindzen 2、支持导出excel 3、根据gs禅道优化导出字段 4、修复部分问题'
__keywords__ = 'xmind2testCase, testcase, test, testing, xmind, 思维导图, XMind思维导图',
__url__ = 'https://github.com/baby-five/xmind2testcase'
__author__ = 'Devin'
__author_email__ = '1324556701@qq.com'
__version__ = '1.6.0'
__license__ = 'MIT'
__cake__ = u'\u2728 \U0001f370 \u2728'
