
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-06T17:31:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3491cb5862bf97eafc30d5ee3971648d6031d1c8",
 "version": "0.6.0.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
