# Generated by Django 4.2.1 on 2023-06-21 16:32

import dj_translation.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('title', dj_translation.models.TranslationField(blank=True, default=dict, null=True)),
                ('description', dj_translation.models.TranslationField(blank=True, default=dict, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
