
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-10T10:18:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0350b8a40fe0da5eee7dc1ef0dc6f3def5ce2a27",
 "version": "1.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
