
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-10T10:10:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd8aa490ea382a54af75bc9e086476854dd2c0f1",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
