# Generated by Django 4.2.6 on 2023-10-08 10:25

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddRangePartition


class Migration(migrations.Migration):

    dependencies = [
        ('clavicle', '0001_initial'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name='DifferentialAnalysis',
            name='DifferentialAnalysis_1_to_1000',
            from_values=1,
            to_values=1000,
        ),
        PostgresAddRangePartition(
            model_name='RawData',
            name='RawData_1_to_1000',
            from_values=1,
            to_values=1000,
        ),
    ]
