import random

komaru_list = ['https://i.postimg.cc/hPn5gZqD/388-worried-face.gif',
               'https://i.postimg.cc/xTPFdG0K/389-upside-down-face.gif',
               'https://i.postimg.cc/pLXc59T3/390-neutral-face.gif', 'https://i.postimg.cc/FzHGd8F3/0.gif',
               'https://i.postimg.cc/x8p5K5q7/0-peach.gif', 'https://i.postimg.cc/VkCgCjwG/1.gif',
               'https://i.postimg.cc/66MMJWz0/1-hammer-and-wrench.gif',
               'https://i.postimg.cc/ZnWphSK7/10-face-with-hand-over-mouth.gif',
               'https://i.postimg.cc/Kj3fDLL8/100-glowing-star.gif',
               'https://i.postimg.cc/8s8HK5BB/101-glowing-star.gif',
               'https://i.postimg.cc/XNZ6zzkp/102-glowing-star.gif',
               'https://i.postimg.cc/ZY1ztxwj/103-glowing-star.gif',
               'https://i.postimg.cc/3Jm5K06h/104-glowing-star.gif',
               'https://i.postimg.cc/RZmrqV5H/105-glowing-star.gif',
               'https://i.postimg.cc/sg4kWds0/106-glowing-star.gif',
               'https://i.postimg.cc/MGsgs7c7/107-glowing-star.gif',
               'https://i.postimg.cc/pdVgYGdV/108-glowing-star.gif',
               'https://i.postimg.cc/PxP90CZB/109-glowing-star.gif',
               'https://i.postimg.cc/Qt41PtsK/11-pleading-face.gif',
               'https://i.postimg.cc/26MMYC73/110-glowing-star.gif',
               'https://i.postimg.cc/cC3j4PFh/111-glowing-star.gif',
               'https://i.postimg.cc/3r0zBD3G/112-glowing-star.gif',
               'https://i.postimg.cc/vHWkRFgH/113-glowing-star.gif',
               'https://i.postimg.cc/pLR7RGzQ/114-glowing-star.gif',
               'https://i.postimg.cc/QMMyWF6H/115-glowing-star.gif',
               'https://i.postimg.cc/k46YfkPC/116-glowing-star.gif',
               'https://i.postimg.cc/HxqZKBTy/117-glowing-star.gif',
               'https://i.postimg.cc/v8nS9FvL/118-glowing-star.gif',
               'https://i.postimg.cc/Qxk44QwF/119-glowing-star.gif',
               'https://i.postimg.cc/Rh2fSDWM/12-enraged-face.gif',
               'https://i.postimg.cc/Mp6shcJd/120-glowing-star.gif',
               'https://i.postimg.cc/q7g1v9RK/121-glowing-star.gif',
               'https://i.postimg.cc/g05NXNXT/122-glowing-star.gif',
               'https://i.postimg.cc/wvmFhLDT/124-glowing-star.gif',
               'https://i.postimg.cc/7h1VR4BF/125-glowing-star.gif',
               'https://i.postimg.cc/4yRPwy1v/126-glowing-star.gif',
               'https://i.postimg.cc/SQcDRLyg/127-glowing-star.gif',
               'https://i.postimg.cc/bN8LtGrp/128-glowing-star.gif',
               'https://i.postimg.cc/vHzhLQx9/129-glowing-star.gif',
               'https://i.postimg.cc/xjZL3ctW/13-face-savoring-food.gif',
               'https://i.postimg.cc/DwpcHBgw/130-glowing-star.gif',
               'https://i.postimg.cc/VNSF8nGB/131-glowing-star.gif',
               'https://i.postimg.cc/yNwyYx2q/132-glowing-star.gif',
               'https://i.postimg.cc/wvLctHd1/133-glowing-star.gif',
               'https://i.postimg.cc/Y07NYVpb/134-glowing-star.gif',
               'https://i.postimg.cc/kGyQccG9/135-glowing-star.gif',
               'https://i.postimg.cc/28zF5P95/136-glowing-star.gif',
               'https://i.postimg.cc/GhqPTq6x/137-glowing-star.gif',
               'https://i.postimg.cc/YC066QHK/138-glowing-star.gif',
               'https://i.postimg.cc/qvF8jgJt/139-glowing-star.gif',
               'https://i.postimg.cc/jdJPgt1C/14-face-with-thermometer.gif',
               'https://i.postimg.cc/HL7bKHn6/140-glowing-star.gif',
               'https://i.postimg.cc/1thD1TNs/141-glowing-star.gif',
               'https://i.postimg.cc/HxwXY2Q5/142-glowing-star.gif',
               'https://i.postimg.cc/NFQT5H4n/143-enraged-face.gif', 'https://i.postimg.cc/WzSZr1Y1/144-woozy-face.gif',
               'https://i.postimg.cc/c1cwPF1G/145-yawning-face.gif',
               'https://i.postimg.cc/jddPTyCw/146-clinking-beer-mugs.gif',
               'https://i.postimg.cc/BQYDnt1h/147-money-with-wings.gif',
               'https://i.postimg.cc/jSDfwKHR/148-skull-and-crossbones.gif',
               'https://i.postimg.cc/2SgZnJGh/149-smiling-face-with-sunglasses.gif',
               'https://i.postimg.cc/mrVHzDPp/15-axe.gif',
               'https://i.postimg.cc/B60PVKdv/150-face-screaming-in-fear.gif',
               'https://i.postimg.cc/C5MBFVMT/151-enraged-face.gif',
               'https://i.postimg.cc/QC6BCnVB/152-man-police-officer.gif',
               'https://i.postimg.cc/kMwRTDwn/153-hushed-face.gif',
               'https://i.postimg.cc/c4Hg2Z5f/154-face-screaming-in-fear.gif',
               'https://i.postimg.cc/JzHy7x8n/155-enraged-face.gif',
               'https://i.postimg.cc/rpSKxpK2/156-confused-face.gif',
               'https://i.postimg.cc/6Qs88Z6h/157-rolling-on-the-floor-laughing.gif',
               'https://i.postimg.cc/pTRyZtFh/158-face-screaming-in-fear.gif',
               'https://i.postimg.cc/G2KtgSFM/159-yawning-face.gif',
               'https://i.postimg.cc/HWr6mGK1/16-unamused-face.gif',
               'https://i.postimg.cc/wMBvCcF9/160-grimacing-face.gif',
               'https://i.postimg.cc/XqDJ4GDd/161-woozy-face.gif',
               'https://i.postimg.cc/mZdhQJ2k/162-face-screaming-in-fear.gif',
               'https://i.postimg.cc/kXBGwsBc/163-grinning-cat.gif', 'https://i.postimg.cc/ncgzWmmt/164-peach.gif',
               'https://i.postimg.cc/7Zz6rL1J/165-woozy-face.gif',
               'https://i.postimg.cc/cJNJxNT9/166-speak-no-evil-monkey.gif',
               'https://i.postimg.cc/3wCxWbcK/167-person-in-tuxedo.gif',
               'https://i.postimg.cc/gJzkhqC3/168-sunrise.gif', 'https://i.postimg.cc/qR1Bx6rS/169-neutral-face.gif',
               'https://i.postimg.cc/dQg4tHPk/17-grinning-face-with-big-eyes.gif',
               'https://i.postimg.cc/0jrkW52Q/170-angry-face.gif', 'https://i.postimg.cc/Fzq92t7x/171-duck.gif',
               'https://i.postimg.cc/BZwQ8FM1/172-confused-face.gif',
               'https://i.postimg.cc/xTJjLd4p/173-thinking-face.gif',
               'https://i.postimg.cc/4NDfPgCf/174-bottle-with-popping-cork.gif',
               'https://i.postimg.cc/L8jH0bRz/175-red-question-mark.gif',
               'https://i.postimg.cc/0Nf99Kzj/176-enraged-face.gif',
               'https://i.postimg.cc/ZR54nYNc/177-face-with-steam-from-nose.gif',
               'https://i.postimg.cc/63bwvsLN/178-red-question-mark.gif',
               'https://i.postimg.cc/brGP063S/179-loudly-crying-face.gif',
               'https://i.postimg.cc/xTHgkvns/18-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/T1Z6tr47/180-sleeping-face.gif',
               'https://i.postimg.cc/J7gM7LzN/181-face-with-steam-from-nose.gif',
               'https://i.postimg.cc/g2bpRHRr/182-fearful-face.gif',
               'https://i.postimg.cc/7Z1kNJM9/183-yen-banknote.gif',
               'https://i.postimg.cc/W42PYp5v/184-thinking-face.gif',
               'https://i.postimg.cc/Pq2ngG78/185-thinking-face.gif', 'https://i.postimg.cc/50yW17cK/186-monkey.gif',
               'https://i.postimg.cc/9Mk5fdCm/187-person-in-bed.gif',
               'https://i.postimg.cc/br2XSZwQ/188-face-with-steam-from-nose.gif',
               'https://i.postimg.cc/z3msCqy4/189-pouting-cat.gif',
               'https://i.postimg.cc/XYk8LnZd/19-face-with-head-bandage.gif',
               'https://i.postimg.cc/05LjWmD1/190-man-gesturing-NO.gif',
               'https://i.postimg.cc/ZKpR1RxB/191-pouting-cat.gif',
               'https://i.postimg.cc/FHvRm4TP/192-yawning-face.gif',
               'https://i.postimg.cc/52mt2RGf/193-face-without-mouth.gif',
               'https://i.postimg.cc/KYv8k5SB/194-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/CKPLjfSt/195-pleading-face.gif',
               'https://i.postimg.cc/G26LfwBx/196-smiling-face-with-sunglasses.gif',
               'https://i.postimg.cc/NMKGbf00/197-oncoming-fist.gif',
               'https://i.postimg.cc/MHR62PV2/198-oncoming-fist.gif', 'https://i.postimg.cc/sDdf9zCV/199-duck.gif',
               'https://i.postimg.cc/6Qx0Ly59/2.gif', 'https://i.postimg.cc/2832CsKf/2-skull-and-crossbones.gif',
               'https://i.postimg.cc/s2nJFK42/20-nerd-face.gif', 'https://i.postimg.cc/02YkV497/200-eyes.gif',
               'https://i.postimg.cc/MpzWNYGN/201-raised-back-of-hand.gif',
               'https://i.postimg.cc/0yZ8sJMQ/202-face-savoring-food.gif',
               'https://i.postimg.cc/zfBqXXKk/203-woman-dancing.gif',
               'https://i.postimg.cc/hG5cJW0R/204-woman-dancing.gif',
               'https://i.postimg.cc/V601nG7r/205-takeout-box.gif',
               'https://i.postimg.cc/RhcBb3xv/206-flushed-face.gif',
               'https://i.postimg.cc/ncJZ91qr/207-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/bYbpv5D4/208-sleepy-face.gif', 'https://i.postimg.cc/bN9Px2RT/209-eye.gif',
               'https://i.postimg.cc/s2fJ0bS8/21-face-savoring-food.gif',
               'https://i.postimg.cc/HkWgBsZC/210-SOS-button.gif', 'https://i.postimg.cc/g2MP5FQL/211-lion.gif',
               'https://i.postimg.cc/W4hPcYcW/212-cat.gif', 'https://i.postimg.cc/GpVnLPcc/213-shield.gif',
               'https://i.postimg.cc/V6tQdS6X/214-person-beard.gif',
               'https://i.postimg.cc/vTdR9Qgk/215-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/PJbgQB1x/216-winking-face.gif', 'https://i.postimg.cc/MZyJwjgS/217-weary-cat.gif',
               'https://i.postimg.cc/8PNQzzVr/218-face-with-open-mouth.gif',
               'https://i.postimg.cc/xT5rJV0p/219-baguette-bread.gif',
               'https://i.postimg.cc/nzCGn73G/22-face-savoring-food.gif',
               'https://i.postimg.cc/bww71Vry/220-person-in-bed.gif',
               'https://i.postimg.cc/GpB65Bv6/221-smiling-face-with-horns.gif',
               'https://i.postimg.cc/fb61nwKy/222-smiling-face-with-smiling-eyes.gif',
               'https://i.postimg.cc/XY1TLKBw/223-weary-cat.gif', 'https://i.postimg.cc/bJkWqKCT/224-cat-face.gif',
               'https://i.postimg.cc/Bb3ybMRG/225-takeout-box.gif',
               'https://i.postimg.cc/L5VW1jMg/226-oncoming-fist.gif',
               'https://i.postimg.cc/BZ5kkf1Z/227-face-savoring-food.gif', 'https://i.postimg.cc/m2bJGpQY/228-foot.gif',
               'https://i.postimg.cc/282JjdwP/229-man-vampire.gif',
               'https://i.postimg.cc/d1pm31XP/23-face-with-monocle.gif',
               'https://i.postimg.cc/nhrWXsSM/230-oncoming-fist.gif',
               'https://i.postimg.cc/XYPzdVtL/231-face-screaming-in-fear.gif',
               'https://i.postimg.cc/5tFkmhVV/232-oncoming-fist.gif', 'https://i.postimg.cc/gJVSC3jt/233-OK-hand.gif',
               'https://i.postimg.cc/NFQJBLrs/234-flushed-face.gif', 'https://i.postimg.cc/v8v2X7pc/235-eyes.gif',
               'https://i.postimg.cc/Dyjj3vfh/236-flushed-face.gif',
               'https://i.postimg.cc/Z5WfTG0d/237-face-with-open-mouth.gif',
               'https://i.postimg.cc/rpWQ451y/238-eye.gif', 'https://i.postimg.cc/4dgwQnP6/239-tangerine.gif',
               'https://i.postimg.cc/52b56DP0/24-confused-face.gif', 'https://i.postimg.cc/tJr5bkjk/240-tongue.gif',
               'https://i.postimg.cc/7Y69VF3W/241-eyes.gif', 'https://i.postimg.cc/8kwwLp6v/242-paw-prints.gif',
               'https://i.postimg.cc/1trBCP7L/243-pencil.gif', 'https://i.postimg.cc/j2qXB9GC/244-sleeping-face.gif',
               'https://i.postimg.cc/8P0HnZwP/245-hot-face.gif',
               'https://i.postimg.cc/XYB8M9DK/246-face-with-symbols-on-mouth.gif',
               'https://i.postimg.cc/PqmQJTHP/247-sleepy-face.gif', 'https://i.postimg.cc/PxTz89fK/248-fire.gif',
               'https://i.postimg.cc/MGkYzXhC/249-face-with-monocle.gif',
               'https://i.postimg.cc/HLLQtX11/25-exploding-head.gif',
               'https://i.postimg.cc/RFd11dNm/250-heart-hands.gif', 'https://i.postimg.cc/prdfsjFF/251-ZZZ.gif',
               'https://i.postimg.cc/8cnh9CRn/252-crown.gif', 'https://i.postimg.cc/dQWmL5bm/253-footprints.gif',
               'https://i.postimg.cc/CLzCDjYy/254-ZZZ.gif', 'https://i.postimg.cc/YqZ6xhqv/255-weary-cat.gif',
               'https://i.postimg.cc/qvK8D4zj/256-weary-cat.gif',
               'https://i.postimg.cc/3wH2PVG7/257-smiling-cat-with-heart-eyes.gif',
               'https://i.postimg.cc/HxYXLM3h/258-kissing-cat.gif', 'https://i.postimg.cc/Twtm5P4Y/259-spider.gif',
               'https://i.postimg.cc/9FGtXcYK/26-airplane.gif', 'https://i.postimg.cc/fykdchG7/260-Christmas-tree.gif',
               'https://i.postimg.cc/fyF95rsG/261-cat-face.gif', 'https://i.postimg.cc/pV1z2pjs/262-weary-cat.gif',
               'https://i.postimg.cc/BQLDt4c4/263-grinning-cat.gif',
               'https://i.postimg.cc/rFB4r3QW/264-jack-o-lantern.gif',
               'https://i.postimg.cc/Dw1Xd6MN/265-party-popper.gif',
               'https://i.postimg.cc/0NxJtmgy/266-carp-streamer.gif',
               'https://i.postimg.cc/1zHVbtPc/267-magic-wand.gif',
               'https://i.postimg.cc/Px5vHj5G/268-heart-on-fire.gif',
               'https://i.postimg.cc/cHkg4bvv/269-wrapped-gift.gif',
               'https://i.postimg.cc/8cLWCbMM/27-flushed-face.gif', 'https://i.postimg.cc/GtBBBxDq/270-CL-button.gif',
               'https://i.postimg.cc/wMS1DRcH/271-Japan.gif', 'https://i.postimg.cc/RC86k2r8/272-crossed-flags.gif',
               'https://i.postimg.cc/65v2tztQ/273-drop-of-blood.gif', 'https://i.postimg.cc/P5nLxZ5Q/274-shower.gif',
               'https://i.postimg.cc/YCNvm94K/275-confetti-ball.gif',
               'https://i.postimg.cc/7LmbmWMK/276-heart-on-fire.gif',
               'https://i.postimg.cc/6Q9yVXR7/277-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/76RhyJR7/278-smiling-face-with-heart-eyes.gif',
               'https://i.postimg.cc/gJjj5Hgm/279-ZZZ.gif', 'https://i.postimg.cc/tTKWycZ9/28-woman-dancing.gif',
               'https://i.postimg.cc/qqCRBMfF/280-exploding-head.gif',
               'https://i.postimg.cc/z3ZfyZ8G/281-red-heart.gif', 'https://i.postimg.cc/WpD6qGTB/282-zany-face.gif',
               'https://i.postimg.cc/L4rktJsn/283-smiling-face-with-heart-eyes.gif',
               'https://i.postimg.cc/L6LtNmqv/284-heart-on-fire.gif',
               'https://i.postimg.cc/g2pv718p/285-expressionless-face.gif',
               'https://i.postimg.cc/52mwWpSC/286-saluting-face.gif',
               'https://i.postimg.cc/KYvtGL0s/287-anxious-face-with-sweat.gif',
               'https://i.postimg.cc/gJxRRpFV/288-hot-face.gif', 'https://i.postimg.cc/pdGzpT7V/289-pleading-face.gif',
               'https://i.postimg.cc/MK8VFhJD/29-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/JnSX5FM9/290-strawberry.gif', 'https://i.postimg.cc/RhfHsT0q/291-waffle.gif',
               'https://i.postimg.cc/bY2kwqR8/292-yawning-face.gif',
               'https://i.postimg.cc/TYMmyBkb/293-face-with-peeking-eye.gif',
               'https://i.postimg.cc/bNxn1LMB/294-face-without-mouth.gif',
               'https://i.postimg.cc/jSR7cPYd/295-enraged-face.gif',
               'https://i.postimg.cc/4xwhSyXv/296-confounded-face.gif',
               'https://i.postimg.cc/g0J6Fp0C/297-smiling-face-with-open-hands.gif',
               'https://i.postimg.cc/MGFfzLMv/298-woman-health-worker.gif',
               'https://i.postimg.cc/QtK9Cq1S/299-smiling-face-with-sunglasses.gif',
               'https://i.postimg.cc/rm8N33r3/3.gif', 'https://i.postimg.cc/9fPBxCry/3-eggplant.gif',
               'https://i.postimg.cc/mZ97VTJk/30-enraged-face.gif',
               'https://i.postimg.cc/90347qB2/300-winking-face-with-tongue.gif',
               'https://i.postimg.cc/ZnrWFKfd/301-smiling-face-with-smiling-eyes.gif',
               'https://i.postimg.cc/2jvLf2zS/302-winking-face.gif',
               'https://i.postimg.cc/28Dbjh6F/303-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/jd4WD2nV/304-ghost.gif',
               'https://i.postimg.cc/7ZP504S5/305-face-with-open-mouth.gif',
               'https://i.postimg.cc/pL0pBSBq/306-heart-hands.gif',
               'https://i.postimg.cc/KYwj6gwT/307-smiling-face-with-heart-eyes.gif',
               'https://i.postimg.cc/zfV32kt5/308-smiling-face.gif', 'https://i.postimg.cc/V6tvmkPV/309-candle.gif',
               'https://i.postimg.cc/Fsg35D9Q/31-money-with-wings.gif',
               'https://i.postimg.cc/7hy66rxY/310-smiling-face-with-halo.gif',
               'https://i.postimg.cc/6qLQ4b3V/311-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/66dqPq07/312-upside-down-face.gif',
               'https://i.postimg.cc/dtw3cFH5/313-zany-face.gif',
               'https://i.postimg.cc/m2jDbnKB/314-winking-face-with-tongue.gif',
               'https://i.postimg.cc/T3PPh9Xm/316-partying-face.gif',
               'https://i.postimg.cc/VkHktCYh/317-face-with-monocle.gif',
               'https://i.postimg.cc/d0ktjV3V/318-nerd-face.gif', 'https://i.postimg.cc/BnSDqH6P/32-unamused-face.gif',
               'https://i.postimg.cc/Qtc8vYpL/320-unamused-face.gif', 'https://i.postimg.cc/HLqWZ184/321-cold-face.gif',
               'https://i.postimg.cc/tJyqbd5s/322-fearful-face.gif',
               'https://i.postimg.cc/VvRYkSGD/323-smiling-face-with-heart-eyes.gif',
               'https://i.postimg.cc/7PMPVcH0/324-shushing-face.gif',
               'https://i.postimg.cc/NfssP4FV/325-confused-face.gif',
               'https://i.postimg.cc/zXxzmgRf/326-face-with-hand-over-mouth.gif',
               'https://i.postimg.cc/T3hRT3rJ/327-heart-hands.gif',
               'https://i.postimg.cc/YCVt0BRK/328-smiling-cat-with-heart-eyes.gif',
               'https://i.postimg.cc/439sh22K/329-weary-face.gif', 'https://i.postimg.cc/x16mq8Jx/33-unamused-face.gif',
               'https://i.postimg.cc/k4P9NNLT/330-person-in-bed.gif',
               'https://i.postimg.cc/zBwNxbr8/331-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/d3qYpssd/332-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/zv0r1svQ/333-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/xjRYHz5P/334-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/pXLvBL1M/335-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/qMDTDH9h/336-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/y8JzwrHf/337-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/0yLqxd59/338-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/TPgvPLhg/339-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/43n9cGpJ/34-nerd-face.gif',
               'https://i.postimg.cc/B639PS1y/340-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/JnQwbfNh/341-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/C5M3Jc7s/342-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/gjMf73BF/343-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/y6v4Wz6Q/344-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/VLvyCHdY/345-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/4NSDbb9p/346-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/R0r22SGF/347-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/d08gYbS9/348-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/9MCKFL6H/349-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/k4bRjyjz/35-face-with-tongue.gif',
               'https://i.postimg.cc/HxzKJQmc/350-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/mkrn7tZd/351-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/QCnymhHj/352-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/gcMQmq41/353-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/3Jd6R4cN/354-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/5NTrF4h3/355-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/Sx9vL0qp/356-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/rmfnyMG5/357-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/xdSFtsTN/358-thumbs-up.gif', 'https://i.postimg.cc/MGb34yvP/359-thumbs-up.gif',
               'https://i.postimg.cc/MHJMgjNT/36-worried-face.gif', 'https://i.postimg.cc/LX9QMnPH/360-thumbs-up.gif',
               'https://i.postimg.cc/d3DWLpnp/361-thumbs-up.gif', 'https://i.postimg.cc/Y0VdgRs9/362-thumbs-up.gif',
               'https://i.postimg.cc/tRmSLR4j/363-face-without-mouth.gif',
               'https://i.postimg.cc/zXbt5myR/364-thinking-face.gif',
               'https://i.postimg.cc/VLx7k7tZ/365-face-with-hand-over-mouth.gif',
               'https://i.postimg.cc/6pCM2dLW/366-enraged-face.gif',
               'https://i.postimg.cc/rpcQSKQS/367-flushed-face.gif',
               'https://i.postimg.cc/Xv8xx4zt/368-pleading-face.gif',
               'https://i.postimg.cc/gJ2sT19j/369-slightly-smiling-face.gif',
               'https://i.postimg.cc/tJdZb4Gz/37-watermelon.gif',
               'https://i.postimg.cc/C1r7TJYN/370-face-with-rolling-eyes.gif',
               'https://i.postimg.cc/mkcwbMgG/371-sun.gif',
               'https://i.postimg.cc/qBYw1m1B/372-smiling-face-with-smiling-eyes.gif',
               'https://i.postimg.cc/6qDhT384/373-upside-down-face.gif',
               'https://i.postimg.cc/wTmVZhrX/374-upside-down-face.gif',
               'https://i.postimg.cc/CxpNgRyW/375-waving-hand.gif',
               'https://i.postimg.cc/3wnCm9yT/376-unamused-face.gif',
               'https://i.postimg.cc/YCNxqtMj/377-neutral-face.gif',
               'https://i.postimg.cc/Gpcx46mK/378-neutral-face.gif',
               'https://i.postimg.cc/26ydwvvB/379-unamused-face.gif', 'https://i.postimg.cc/NGRrmp2r/38-woozy-face.gif',
               'https://i.postimg.cc/50rBk0qK/380-neutral-face.gif',
               'https://i.postimg.cc/KjgPX20G/381-neutral-face.gif',
               'https://i.postimg.cc/Bt9x4Vzx/382-night-with-stars.gif',
               'https://i.postimg.cc/KvBWBSmh/383-smiling-face-with-smiling-eyes.gif',
               'https://i.postimg.cc/L4qw4g7X/384-smiling-face-with-smiling-eyes.gif',
               'https://i.postimg.cc/sft8MDdJ/385-face-screaming-in-fear.gif',
               'https://i.postimg.cc/RZmDTs06/386-smiling-face-with-smiling-eyes.gif',
               'https://i.postimg.cc/QdqnYQB6/387-new-moon-face.gif',
               'https://i.postimg.cc/c4mg5Cmx/39-pensive-face.gif',
               'https://i.postimg.cc/y84YVH8J/391-fearful-face.gif',
               'https://i.postimg.cc/PqKtzvzZ/392-slightly-smiling-face.gif',
               'https://i.postimg.cc/NMzBZhnj/393-unamused-face.gif',
               'https://i.postimg.cc/sDZgdXsd/394-smirking-face.gif',
               'https://i.postimg.cc/pdPWFJ8R/395-slightly-frowning-face.gif',
               'https://i.postimg.cc/7Z3PhW5K/396-face-with-monocle.gif',
               'https://i.postimg.cc/hjjKC4pY/397-laptop.gif',
               'https://i.postimg.cc/gjLmWS9q/398-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/gcxZjGm4/399-unamused-face.gif',
               'https://i.postimg.cc/QNYJY6xY/4-face-screaming-in-fear.gif',
               'https://i.postimg.cc/Sxx204TW/40-ghost.gif', 'https://i.postimg.cc/KcCggCYb/400-pile-of-poo.gif',
               'https://i.postimg.cc/xTHNGgkz/401-unamused-face.gif', 'https://i.postimg.cc/jS4Wm54q/402-eyes.gif',
               'https://i.postimg.cc/FKFf44Ty/403-sleeping-face.gif',
               'https://i.postimg.cc/d0WhQxfz/404-face-with-rolling-eyes.gif',
               'https://i.postimg.cc/4dmmY1kn/405-sleeping-face.gif',
               'https://i.postimg.cc/13Qnv66Y/406-star-struck.gif',
               'https://i.postimg.cc/zB63KR87/407-pleading-face.gif',
               'https://i.postimg.cc/GtDtQhpC/408-face-with-raised-eyebrow.gif',
               'https://i.postimg.cc/7PJ5DXnW/409-oncoming-fist.gif',
               'https://i.postimg.cc/VkZSmhp2/41-drooling-face.gif',
               'https://i.postimg.cc/wTK7BJWT/410-face-with-open-mouth.gif',
               'https://i.postimg.cc/kXxDR4ZN/411-exploding-head.gif',
               'https://i.postimg.cc/FHNzyv5M/412-unamused-face.gif',
               'https://i.postimg.cc/0ynQZ49b/413-neutral-face.gif',
               'https://i.postimg.cc/3wwwqZw9/414-unamused-face.gif',
               'https://i.postimg.cc/cJ5JG8gW/415-pleading-face.gif',
               'https://i.postimg.cc/632pW5nv/416-upside-down-face.gif',
               'https://i.postimg.cc/nzycCbGw/417-face-without-mouth.gif', 'https://i.postimg.cc/PJ1fD36f/418-cat.gif',
               'https://i.postimg.cc/66ZpFq9s/419-cat.gif', 'https://i.postimg.cc/mrcPDwGk/42-ghost.gif',
               'https://i.postimg.cc/dtKVFF1h/420-cat.gif', 'https://i.postimg.cc/tCtCCcZ2/421-cat.gif',
               'https://i.postimg.cc/htD4J0Vg/422-cat.gif', 'https://i.postimg.cc/cLFxf8c3/423-cat.gif',
               'https://i.postimg.cc/nLMH2cdP/424-cat.gif', 'https://i.postimg.cc/HLKThDRs/425-cat.gif',
               'https://i.postimg.cc/4d9XC2Rv/426-cat.gif', 'https://i.postimg.cc/Xq64nKnR/427-cat.gif',
               'https://i.postimg.cc/rsGcsdmK/428-cat.gif', 'https://i.postimg.cc/J7jRPFqM/429-cat.gif',
               'https://i.postimg.cc/g0fn6ZYD/43-glowing-star.gif', 'https://i.postimg.cc/WbjTK7Wr/430-cat.gif',
               'https://i.postimg.cc/522192M2/431-cat.gif', 'https://i.postimg.cc/bwVPZfzH/432-cat.gif',
               'https://i.postimg.cc/CLNSVfX2/433-brick.gif', 'https://i.postimg.cc/cJKSYkCq/434-brick.gif',
               'https://i.postimg.cc/k5kdyNR2/435-brick.gif', 'https://i.postimg.cc/NFtq3g4Y/436-brick.gif',
               'https://i.postimg.cc/Qt1ZYBc0/437-brick.gif', 'https://i.postimg.cc/3NZ57PSG/438-brick.gif',
               'https://i.postimg.cc/05GqpwkN/439-dashing-away.gif',
               'https://i.postimg.cc/LXLhk85M/44-man-police-officer.gif',
               'https://i.postimg.cc/1591M3Xr/440-smiling-face-with-heart-eyes.gif',
               'https://i.postimg.cc/gkNF7b6F/441-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/2SyRR94q/442-pouting-cat.gif',
               'https://i.postimg.cc/XYPMVK8s/443-astonished-face.gif',
               'https://i.postimg.cc/9fw6z4gC/444-cowboy-hat-face.gif',
               'https://i.postimg.cc/fL46dw1X/445-cold-face.gif',
               'https://i.postimg.cc/SsWH7BpP/446-left-facing-fist.gif',
               'https://i.postimg.cc/yxstfL18/447-cherry-blossom.gif', 'https://i.postimg.cc/8c43xLcB/448-skull.gif',
               'https://i.postimg.cc/G3xZBnK8/449-grimacing-face.gif',
               'https://i.postimg.cc/3NhNtQ00/45-glowing-star.gif', 'https://i.postimg.cc/m2ZKCppd/450-weary-cat.gif',
               'https://i.postimg.cc/xTshRGW9/451-new-moon-face.gif', 'https://i.postimg.cc/3xd6b4Tm/452-kangaroo.gif',
               'https://i.postimg.cc/BnkyWSSy/453-face-savoring-food.gif',
               'https://i.postimg.cc/pdjSRwyd/454-face-screaming-in-fear.gif',
               'https://i.postimg.cc/tTHMTBVN/455-kissing-face-with-closed-eyes.gif',
               'https://i.postimg.cc/MTbrj172/456-clown-face.gif', 'https://i.postimg.cc/9XbnmtXy/457-enraged-face.gif',
               'https://i.postimg.cc/HsLPVcjR/458-smiling-face.gif',
               'https://i.postimg.cc/YqyDgrW9/459-flushed-face.gif',
               'https://i.postimg.cc/yxTd5p0Q/46-glowing-star.gif',
               'https://i.postimg.cc/rw0nNB19/460-smiling-face-with-hearts.gif',
               'https://i.postimg.cc/SxBZTgVb/461-confused-face.gif',
               'https://i.postimg.cc/Dz1xt1YJ/462-frowning-face-with-open-mouth.gif',
               'https://i.postimg.cc/4dZWZnr8/463-weary-face.gif',
               'https://i.postimg.cc/4d5B3sGX/464-angry-face-with-horns.gif',
               'https://i.postimg.cc/WpmhhzxG/47-boy.gif', 'https://i.postimg.cc/yYVW9Bzw/48-glowing-star.gif',
               'https://i.postimg.cc/wT0MQPq3/49-glowing-star.gif', 'https://i.postimg.cc/3JyCsgk8/5-shushing-face.gif',
               'https://i.postimg.cc/sgL2thZr/50-glowing-star.gif', 'https://i.postimg.cc/7Zh6sVh9/51-glowing-star.gif',
               'https://i.postimg.cc/DzbzFwqb/52-glowing-star.gif', 'https://i.postimg.cc/TwM3Pv9N/53-glowing-star.gif',
               'https://i.postimg.cc/sXYDQHHj/54-glowing-star.gif', 'https://i.postimg.cc/4yX4zvjz/55-magic-wand.gif',
               'https://i.postimg.cc/j2vxvwrB/56-glowing-star.gif', 'https://i.postimg.cc/1RK3yTNM/57-glowing-star.gif',
               'https://i.postimg.cc/tCCCJ53b/58-glowing-star.gif', 'https://i.postimg.cc/jdgq77c7/59-glowing-star.gif',
               'https://i.postimg.cc/JzZ3nM3S/6-face-with-symbols-on-mouth.gif',
               'https://i.postimg.cc/y8D1X8pr/60-glowing-star.gif', 'https://i.postimg.cc/2SgzHNPj/61-glowing-star.gif',
               'https://i.postimg.cc/TPmTFH6V/62-glowing-star.gif', 'https://i.postimg.cc/zBrqrSz9/63-glowing-star.gif',
               'https://i.postimg.cc/KzDxvk44/64-glowing-star.gif', 'https://i.postimg.cc/3Nr7y8D1/65-glowing-star.gif',
               'https://i.postimg.cc/1XWSwkGQ/66-glowing-star.gif', 'https://i.postimg.cc/NGbB3HWz/67-glowing-star.gif',
               'https://i.postimg.cc/Gh2ddpRh/68-glowing-star.gif', 'https://i.postimg.cc/Vk0w0H5x/69-glowing-star.gif',
               'https://i.postimg.cc/Dzhr4HB0/7-zipper-mouth-face.gif',
               'https://i.postimg.cc/yNqHmXZk/70-glowing-star.gif', 'https://i.postimg.cc/pdDtqhfk/71-glowing-star.gif',
               'https://i.postimg.cc/W3TcKNSV/72-glowing-star.gif', 'https://i.postimg.cc/tJgQqBLm/73-glowing-star.gif',
               'https://i.postimg.cc/4yFCmzG4/74-glowing-star.gif',
               'https://i.postimg.cc/bY6fCjnX/75-grinning-face.gif',
               'https://i.postimg.cc/BQX9Rw5j/76-glowing-star.gif', 'https://i.postimg.cc/wjNKjyGH/77-glowing-star.gif',
               'https://i.postimg.cc/fTpnsj5B/78-glowing-star.gif', 'https://i.postimg.cc/DzQtqVhM/79-glowing-star.gif',
               'https://i.postimg.cc/g0KvVsTD/8-frowning-face.gif', 'https://i.postimg.cc/cJGpgxp3/80-glowing-star.gif',
               'https://i.postimg.cc/W32x89bb/81-glowing-star.gif', 'https://i.postimg.cc/mD8J5Qt3/82-glowing-star.gif',
               'https://i.postimg.cc/cCC2yrnp/83-glowing-star.gif', 'https://i.postimg.cc/v82C7tRb/84-glowing-star.gif',
               'https://i.postimg.cc/qM9YSBMF/85-student.gif', 'https://i.postimg.cc/MpV4Sknp/86-pig-face.gif',
               'https://i.postimg.cc/rFd3fRcW/87-glowing-star.gif', 'https://i.postimg.cc/zfNQDdhS/88-duck.gif',
               'https://i.postimg.cc/zfkcynSm/89-speak-no-evil-monkey.gif',
               'https://i.postimg.cc/ydY0v9qz/9-banana.gif', 'https://i.postimg.cc/LXCQT2bN/90-oncoming-fist.gif',
               'https://i.postimg.cc/yxDQp2qB/91-slightly-frowning-face.gif',
               'https://i.postimg.cc/bJNFks3Z/92-glowing-star.gif', 'https://i.postimg.cc/Wpyfqpr4/93-glowing-star.gif',
               'https://i.postimg.cc/DybprVdP/94-glowing-star.gif', 'https://i.postimg.cc/VkQG47KQ/95-glowing-star.gif',
               'https://i.postimg.cc/vmGPw4R0/96-glowing-star.gif', 'https://i.postimg.cc/s2KTj3ss/97-glowing-star.gif',
               'https://i.postimg.cc/B66MtRnD/98-glowing-star.gif', 'https://i.postimg.cc/hj5MmMXY/99-glowing-star.gif']


def get_random_komaru():
    return random.choice(komaru_list)

def get_all_komaru():
    return '\n'.join(komaru_list)

def get_komaru(list_index):
    if list_index < len(komaru_list):
        return komaru_list[list_index]
    else:
        raise Exception(f"Кол-во фото комару на данный момент: {len(komaru_list)}\nВаш номер за пределом значений")
