"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Cadence(str, Enum):
    ANNUAL = 'annual'
    MONTHLY = 'monthly'
    QUARTERLY = 'quarterly'
