
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-10T15:58:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8af1db1b47adc410cee99a672d6ade451cee1e2",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
