# coding: utf-8

"""
    BIND Public API

    Description for BIND.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@bind.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.main_pool_get_pool_size_history.get import GetMainPoolSizeHistoryTest


class MainPoolApi(
    GetMainPoolSizeHistoryTest,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
