
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-09T15:22:59+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f12c743f39b9110fb3bef0b27f22549da4da7f19",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
