#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2304-142-g06d6780c"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2304
#define NETGEN_VERSION_TWEAK 142
#define NETGEN_VERSION_HASH "g06d6780c"
#endif // NETGEN_VERSION_HPP_INCLUDED
