from enum import Enum
from os import PathLike

PATH = str | bytes | PathLike


class IDE(Enum):
    PYCHARM = ...
    INTELLIJ_IDEA = ...
    PHPSTORM = ...
    RIDER = ...
    WEBSTORM = ...
    CLION = ...
    GOLANG = ...
    RUBYMINE = ...


def is_installed(ide: IDE) -> bool: ...


def open(ide: IDE, *paths: PATH, line: int = ..., column: int = ...) -> None: ...


def compare_files(ide: IDE, path1: PATH, path2: PATH, path3: PATH = ...) -> None: ...


def format_files(ide: IDE, *paths: PATH, mask: str = ..., recursive: bool = ...) -> None: ...
