# coding: utf-8

"""
    Chain App BIND client SDK

    Description for BIND. 

    The version of the OpenAPI document: 2.0
    Contact: support@bind.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr

class Stake(BaseModel):
    """
    Stake
    """
    amount: Union[StrictFloat, StrictInt] = Field(...)
    user_id: StrictStr = Field(...)
    locking_period: Union[StrictFloat, StrictInt] = Field(...)
    is_checking_fee: StrictBool = Field(...)
    __properties = ["amount", "user_id", "locking_period", "is_checking_fee"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Stake:
        """Create an instance of Stake from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Stake:
        """Create an instance of Stake from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Stake.parse_obj(obj)

        _obj = Stake.parse_obj({
            "amount": obj.get("amount"),
            "user_id": obj.get("user_id"),
            "locking_period": obj.get("locking_period"),
            "is_checking_fee": obj.get("is_checking_fee")
        })
        return _obj


