# Generated by Django 4.2.6 on 2023-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_nequi", "0002_alter_nequicredential_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="nequicredential",
            name="test_cellphone",
            field=models.CharField(
                blank=True,
                default="3000000000",
                help_text="Test Cellphone",
                max_length=255,
                null=True,
                verbose_name="Test Cellphone",
            ),
        ),
        migrations.AddField(
            model_name="nequicredential",
            name="test_mode",
            field=models.BooleanField(
                default=True, help_text="Test Mode", verbose_name="Test Mode"
            ),
        ),
    ]
