# Generated by Django 4.2.6 on 2023-10-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_nequi", "0005_alter_nequitransaction_other_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="nequitransaction",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID",
                max_length=255,
                null=True,
                verbose_name="Transaction ID",
            ),
        ),
    ]
