# Generated by Django 4.2.6 on 2023-10-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_nequi", "0007_nequitransaction_value_nequitransactionhisory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nequitransactionhisory",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="nequitransactionhisory",
            name="payment_status",
            field=models.CharField(
                blank=True,
                help_text="Payment Status",
                max_length=255,
                null=True,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="nequitransactionhisory",
            name="status_code",
            field=models.CharField(
                blank=True,
                help_text="Status Code",
                max_length=255,
                null=True,
                verbose_name="Status Code",
            ),
        ),
        migrations.AlterField(
            model_name="nequitransactionhisory",
            name="status_description",
            field=models.CharField(
                blank=True,
                help_text="Status Description",
                max_length=255,
                null=True,
                verbose_name="Status Description",
            ),
        ),
        migrations.AlterField(
            model_name="nequitransactionhisory",
            name="value",
            field=models.CharField(
                blank=True,
                help_text="Value",
                max_length=255,
                null=True,
                verbose_name="Value",
            ),
        ),
    ]
