
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-10T20:36:40-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "2f2cb5930b0b85e3e81267c8163a0060c8e61596",
 "version": "3.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
