# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.21.19.dev53+g64a387ed.d20230328"
__version_tuple__ = version_tuple = (0, 21, 19, "dev53", "g64a387ed.d20230328")
