
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-06T07:03:20+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "9e6e1922c829d6d4b0296f4d0c660a123b720937",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
