# Computational Biology Python Tools
#
#
# Packages included in this file:
#   - dnaToolkit.py
#
# https://www.stephendoescomp.bio
# Stephen Cheney © 2023

from bio_seq import *
from aa_seq import *
from fasta_tk import *


class main:
   dna = bio_seq("GGTTTCCATCGCATGTGCGCTCCGAGTCCCTTCCTGAGCACGTCAAGCGGGCCGTACGAGATCTATAGTTAGGTAGACAGCTGGTGCAAAGACTAACCCGGCTGGTCGTGAGGACCTTGGACGGACTGTCAAAGCCTCGTATGTCCTCACAAGCCAGATTAGTGGTCCTACCCCACATATAGGGTGCGTGACCGCTGGCTAAGCAATTTCTATGCAGGGAATGTTTCTTTCCCTTTGGTCGCGACACTACAGAGCCTCGGGACTTGACAGTAATGTTAATCAGTCAAACGCCCTGTGCTTAGGTCATACGCACATTCTTTAGACAACCTGATTGCTGACGAATTGGACACTTGGCAATTTCAGGCCGTTATCTCTATCCATATACACGGTTTTAAAAAGCTCAGGCACTCTAAAAGGTCAGGGGAACAAAGGTCTGTCGTATAGGCAACTTTCGTAGCCTCAGAGACTTCACGGGATATGCATTCACTGTAGTCACATTTTCTGGTATTCGCAGACCGGCTGGTAACTCTCAACTAGTTGTCTCGACACATAGAGCGTAAATCTGACATCTCGTCCCGAACTGCACACGTCGCTAGGTACCCAAGGCGTGTATGCGCCATAGTTCCCCTAGAGAACAGTTACATACGGATCTCGAGATCAAGAAGACTGAACAGCAACCCTTTTCGTACTTCTACTAGCAGAATCGTGGGCTCGGTCCTGGAATAACGAAAAGTTTCAGCAGTTCCACTTGGAGACAGGGGCTTTCTCTATTTGCAGAACATTGGCTTGTGCTGAACGATGCCATTAAGGGCGAGCTCCTAATGTCTTGCTACTATATTAACTATTCGGTACCCGGGCAGTTAGCTCGATTCAAAACAAAGTGATGGGACGAACGCAATCAACGTTGACACAGGTCCAAAGTGCAAAGTAGACCGTCAAGGTAGTAACAGC")
   rna = bio_seq('AUGACGUUUA','RNA')
   print(dna.transcribe().getAllORFProteins(ordered = True))

   print(dfFromFASTA('test.fasta', 'DNA'))
   
   s1 = bio_seq('TAGATG')
   s2 = bio_seq('CCTATAGG')
   output = s1.globalAlign(s2, 2, -1, -3. -.5)
   print('\n\n')
   print(output[0].seqCompare(output[1]))
   print(f'Score: {output[2]}')
   
   fastaSeqs = parseFASTA('test2.fasta', seq_type='DNA')
   output = fastaSeqs[0].globalAlign(fastaSeqs[1])
   print(output[0].seqCompare(output[1]))
   print(f'Score: {output[2]}')
   
   ancestryToFASTA('AncestryDNA.txt', 'test_fa.fasta', 2)

main()