# coding: utf-8

"""
    Dungeons and Trolls

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool
from dungeons_and_trolls_client.models.dungeonsandtrolls_position import DungeonsandtrollsPosition

class DungeonsandtrollsFogOfWarMap(BaseModel):
    """
    DungeonsandtrollsFogOfWarMap
    """
    position: Optional[DungeonsandtrollsPosition] = None
    fog_of_war: Optional[StrictBool] = Field(None, alias="fogOfWar")
    __properties = ["position", "fogOfWar"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DungeonsandtrollsFogOfWarMap:
        """Create an instance of DungeonsandtrollsFogOfWarMap from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of position
        if self.position:
            _dict['position'] = self.position.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DungeonsandtrollsFogOfWarMap:
        """Create an instance of DungeonsandtrollsFogOfWarMap from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DungeonsandtrollsFogOfWarMap.parse_obj(obj)

        _obj = DungeonsandtrollsFogOfWarMap.parse_obj({
            "position": DungeonsandtrollsPosition.from_dict(obj.get("position")) if obj.get("position") is not None else None,
            "fog_of_war": obj.get("fogOfWar")
        })
        return _obj


