# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/00_config.ipynb.

# %% auto 0
__all__ = ['R_sun', 'R_jup']

# %% ../notebooks/api/00_config.ipynb 6
# R_sun = 696392e3
R_sun = spice.bodvrd("SUN", "RADII", 3)[1][0] * 1e3
R_sun

# %% ../notebooks/api/00_config.ipynb 7
# R_jup = 69911e3
R_jup = np.mean(spice.bodvrd("JUPITER", "RADII", 3)[1])
R_jup
