# Generated by Django 4.1.1 on 2023-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharefile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="keystring",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
