# Generated by Django 4.1.1 on 2023-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharefile", "0002_alter_fileupload_keystring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="keystring",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
