
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-11T10:42:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c4aebdc7fd40a817a951b05a0f52518f1e373d1",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
