#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2304-140-gdd06cbad"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2304
#define NETGEN_VERSION_TWEAK 140
#define NETGEN_VERSION_HASH "gdd06cbad"
#endif // NETGEN_VERSION_HPP_INCLUDED
