# Generated by Django 4.2.1 on 2023-07-08 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import edc_sites.model_mixins


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("edc_reference", "0011_auto_20200929_0238"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reference",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", edc_sites.model_mixins.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="reference",
            name="site",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
    ]
