
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-06T15:27:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2be6e50b5790b74f40c977a1d9e2fe7addf42e78",
 "version": "1.0.0rc14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
