# Generated by Django 4.2.1 on 2023-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="azure_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="job_title",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
