# Generated by Django 2.2 on 2022-12-21 12:07

from django.db import migrations, models
import wcd_folders_backuper.conf


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.FileField(upload_to=wcd_folders_backuper.conf.default_path, verbose_name='Backup')),
                ('source', models.TextField(verbose_name='Source location')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
