
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-10T01:12:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b1edb2f98ecb6470883acd90450f93b5f0426fa",
 "version": "0.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
