
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-10T14:14:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9a7de7e5f6c3651e1dde4bdf64dfe27d1775785",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
