
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-09T13:41:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "77d82033e634ed82b9442af1b8d37a7a7e1cc00d",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
