# Generated by Django 4.2.6 on 2023-10-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artd_partner", "0001_initial"),
        ("artd_nequi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nequicredential",
            name="partner",
            field=models.OneToOneField(
                help_text="Partner",
                on_delete=django.db.models.deletion.CASCADE,
                to="artd_partner.partner",
                verbose_name="Partner",
            ),
        ),
    ]
