# Generated by Django 4.2.6 on 2023-10-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_nequi", "0003_nequicredential_test_cellphone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nequitransaction",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="nequitransaction",
            name="client_id",
            field=models.CharField(
                default="",
                help_text="Client ID",
                max_length=255,
                verbose_name="Client ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nequitransaction",
            name="message_id",
            field=models.CharField(
                default="",
                help_text="Message ID",
                max_length=255,
                verbose_name="Message ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nequitransaction",
            name="status_code",
            field=models.CharField(
                blank=True,
                help_text="Status Code",
                max_length=255,
                null=True,
                verbose_name="Status Code",
            ),
        ),
        migrations.AddField(
            model_name="nequitransaction",
            name="status_description",
            field=models.CharField(
                blank=True,
                help_text="Status Description",
                max_length=255,
                null=True,
                verbose_name="Status Description",
            ),
        ),
    ]
