# Generated by Django 4.2.6 on 2023-10-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artd_nequi", "0004_remove_nequitransaction_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nequitransaction",
            name="other_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Other Data",
                null=True,
                verbose_name="Other Data",
            ),
        ),
    ]
