# Generated by Django 4.2.6 on 2023-10-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artd_nequi", "0006_nequitransaction_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="nequitransaction",
            name="value",
            field=models.CharField(
                blank=True,
                help_text="Value",
                max_length=255,
                null=True,
                verbose_name="Value",
            ),
        ),
        migrations.CreateModel(
            name="NequiTransactionHisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created at",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated at", verbose_name="Updated at"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="Status", verbose_name="Status"
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        help_text="Message ID",
                        max_length=255,
                        verbose_name="Message ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        help_text="Payment Status",
                        max_length=255,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value", max_length=255, verbose_name="Value"
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        help_text="Status Code",
                        max_length=255,
                        verbose_name="Status Code",
                    ),
                ),
                (
                    "status_description",
                    models.CharField(
                        help_text="Status Description",
                        max_length=255,
                        verbose_name="Status Description",
                    ),
                ),
                (
                    "other_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Other Data",
                        null=True,
                        verbose_name="Other Data",
                    ),
                ),
                (
                    "nequi_transaction",
                    models.ForeignKey(
                        help_text="Nequi Transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artd_nequi.nequitransaction",
                        verbose_name="Nequi Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nequi Transaction History",
                "verbose_name_plural": "Nequi Transaction Histories",
            },
        ),
    ]
